[supervisord]
nodaemon=true
user=root

[program:xvfb]
command=Xvfb :1 -screen 0 1280x720x24 -ac +extension GLX +render -noreset
autorestart=true
priority=1

[program:x11vnc]
command=x11vnc -display :1 -nopw -forever -shared -rfbport 5900
autorestart=true
priority=2

[program:chromium]
command=chromium-browser --no-sandbox --disable-gpu --disable-dev-shm-usage --window-position=0,0 --window-size=1280,720 --start-maximized --display=:1 https://vulnx.dev
autorestart=true
priority=3
